# This file was generated by GoReleaser. DO NOT EDIT.
cask "issuebot" do
  name "issuebot"
  desc "Autonomous GitHub issue processor powered by any CLI tool"
  homepage "https://github.com/tinybluerobots/issuebot"
  version "1.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "issuebot"

  on_macos do
    on_intel do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_darwin_amd64.tar.gz"
      sha256 "bb97b9ad7241a8b5d89f442f0170b487e597e3284adde9b392959ea08fcf3b45"
    end
    on_arm do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_darwin_arm64.tar.gz"
      sha256 "4970088f9f11bb8f3a166d29badeef3cf454cb370682f9786811a0c55b1807ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_linux_amd64.tar.gz"
      sha256 "5942ee9584e4c5040ff28861beb24e04d2621cc69b5609357ac6884644f3b324"
    end
    on_arm do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_linux_arm64.tar.gz"
      sha256 "f0609c6ac2966c1e66ae76264e4ed564f7213ad9827cafc855ef77c50d07a5e6"
    end
  end

  # No zap stanza required
end
