# This file was generated by GoReleaser. DO NOT EDIT.
cask "issuebot" do
  version "1.7.0"

  on_macos do
    on_intel do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_darwin_amd64.tar.gz"
      sha256 "a83db442d57116c57f8d36bfc8f5505044741dd740b4b0b8a74474339a7f8e09"
    end
    on_arm do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_darwin_arm64.tar.gz"
      sha256 "8b46137b13897cfb9d650247e7e5d05e14dc8ea201b75470a226c7408907f6f2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_linux_amd64.tar.gz"
      sha256 "56a87315da5b79e38de64122ab1cdebe49510ff4fe9bf44f934d643f246ce43e"
    end
    on_arm do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_linux_arm64.tar.gz"
      sha256 "ab0315f9a037d898109188c808119bba4ab23e703adfe0f67d9b9bdd798453a6"
    end
  end

  name "issuebot"
  desc "Autonomous GitHub issue processor powered by any CLI tool"
  homepage "https://github.com/tinybluerobots/issuebot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "issuebot"

  # No zap stanza required

end
