# This file was generated by GoReleaser. DO NOT EDIT.
cask "issuebot" do
  name "issuebot"
  desc "Autonomous GitHub issue processor powered by any CLI tool"
  homepage "https://github.com/tinybluerobots/issuebot"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "issuebot"

  on_macos do
    on_intel do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_darwin_amd64.tar.gz"
      sha256 "f3c4cd2602e9106e384cd6993a436f93e5473784cef68857ee9566543f9dfb06"
    end
    on_arm do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_darwin_arm64.tar.gz"
      sha256 "a8c7e2409e1623d55a8df998e620db230b12d39acc582aa835e13b522bfa746d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_linux_amd64.tar.gz"
      sha256 "ff0cb916a78fb2c48f44dc9c3a087de1a52a274cf36ba6c33a5da1db85409c91"
    end
    on_arm do
      url "https://github.com/tinybluerobots/issuebot/releases/download/v#{version}/issuebot_#{version}_linux_arm64.tar.gz"
      sha256 "eb35afc5bc6a71670048bd8decba3dda701bc845db02271ad0012644359f900b"
    end
  end

  # No zap stanza required
end
